// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY'] ?? 'Firebase API key not found',
    appId: '1:747915225879:web:372187f93e9724577d6552',
    messagingSenderId: '747915225879',
    projectId: 'splitmate-b6eaa',
    authDomain: 'splitmate-b6eaa.firebaseapp.com',
    storageBucket: 'splitmate-b6eaa.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'] ?? 'Firebase API key not found',
    appId: '1:747915225879:android:eeb6de9a61913a9f7d6552',
    messagingSenderId: '747915225879',
    projectId: 'splitmate-b6eaa',
    storageBucket: 'splitmate-b6eaa.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] ?? 'Firebase API key not found',
    appId: '1:747915225879:ios:755e9bf0158a4af27d6552',
    messagingSenderId: '747915225879',
    projectId: 'splitmate-b6eaa',
    storageBucket: 'splitmate-b6eaa.firebasestorage.app',
    iosBundleId: 'com.example.splitMate',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY'] ?? 'Firebase API key not found',
    appId: '1:747915225879:ios:755e9bf0158a4af27d6552',
    messagingSenderId: '747915225879',
    projectId: 'splitmate-b6eaa',
    storageBucket: 'splitmate-b6eaa.firebasestorage.app',
    iosBundleId: 'com.example.splitMate',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_API_KEY'] ?? 'Firebase API key not found',
    appId: '1:747915225879:web:b4446871eaed5bc27d6552',
    messagingSenderId: '747915225879',
    projectId: 'splitmate-b6eaa',
    authDomain: 'splitmate-b6eaa.firebaseapp.com',
    storageBucket: 'splitmate-b6eaa.firebasestorage.app',
  );
}
